//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int ID_device { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string OS { get; set; }
        public string OS_version { get; set; }
        public string Processor { get; set; }
        public Nullable<byte> RAM { get; set; }
        public Nullable<int> Owner { get; set; }
    
        public virtual User User { get; set; }
    }
}
